variables:
  PACKAGE_NAME: "recruit"
  PROD_ENV_1: "10.166.41.101"
image: node:latest
stages: # 分段
  - install
  - deploy

cache: # 缓存
  paths:
    - node_modules
    - build

install-job:
  stage: install
  only:
    - dev
    - master
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm config set registry https://registry.npm.taobao.org/
    - npm install
    - echo "installing......"
    - npx browserslist@latest --update-db
    - npm run build
    - echo "building......"
    - "ls -al"
    - "mkdir -p ~/.ssh && chmod 700 ~/.ssh/"
    - 'echo "$SSH_PRIVATE_KEY" >> ./id_rsa && chmod 600 ./id_rsa'
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - "ls -al"
    - 'ssh -i ./id_rsa root@$PROD_ENV_1 "rm -rf /home/front_end/$PACKAGE_NAME"'
    - echo "delete succeeded"
    - "scp -i ./id_rsa -r $PACKAGE_NAME root@$PROD_ENV_1:/home/front_end/$PACKAGE_NAME"

deploy-job:
  stage: deploy
  only:
    - dev
    - master
  script:
    - echo "deploy succeeded!"
